import bcrypt from 'bcryptjs';

const Data={
    users: [
        {
            name: 'Waseem',
            email: 'waseemaijaz2020@gmail.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
            isSeller: true,
            seller: {
                name: 'waseem',
                logo: '../Images/logo1.jpg',
                description: 'Best seller',
                rating: 4.5,
                numReviews: 120,
                },
        },
        
    ],
    products :[ {
        name: 'ShellFort Cat',
        category: 'Cats',
        image: '../Images/cats/caty1.jpeg',
        price: 110,
        countInStock:2,
        rating: 4.5,
        numReviews: 10,
        description: '',
    },
    {
        name: 'Dog',
        category: 'Dogs',
        image: '../Images/dogs/dogmask.jpeg',
        price: 240,
        countInStock:5,
        rating: 4.9,
        numReviews: 7,
        description: 'Life expectancy: 8 – 10 years,Height: Female: 31–40 cm, Male: 31–40 cm,Weight: Female: 18–23 kg, Male: 23–25 kg,Colors: White, Fawn, Piebald, Brindle & White, Fawn & White, Red Brindle, Red & White, Red,Other names:English Bulldog, British Bulldog',
    },
    {
        name: 'Murgha',
        category: 'Cocks',
        image: '../Images/birds/ik.jpeg',
        price: 200,
        countInStock:10,
        rating: 4.7,
        numReviews:11,
        description: 'color black, age 6 months, full trained, active and healthy',
    },
    {
         name: 'Puppy',
         category: 'Dogs',
         image: '../Images/dogs/dog6.jpg',
         price: 190,
         countInStock:0,
         rating: 4.7,
         numReviews:11,
         description: 'Trained dog and very Friendly',
     },
    {
        name: 'Rabit',
        category: 'Rabits',
        image: '../Images/rabbit/rabbit3.jpg',
        price: 78,
        countInStock:15,
        rating: 4.6,
        numReviews:3,
        description: 'Trained Rabbit and very Friendly',
    },
    {
        name: 'Jelly Fish',
        category: 'Fishes',
        image: '../Images/fish/fish8.jpg',
        price:30,
        countInStock:7,
        rating:4.8,
        numReviews:12,
        description: 'Trained Fish and very Friendly',
    },
    {
        name: 'Cat',
        category: 'Cats',
        image: '../Images/cats/cat13.jpg',
        price:100,
        countInStock:4,
        rating: 4.4,
        numReviews: 10,
        description: 'Trained cat and very Friendly',
    },
    {
        name: 'cock Hen',
        category: 'Cock',
        image: '../Images/birds/cock1.jpg',
        price:120,
        countInStock:25,
        rating: 4.9,
        numReviews:7,
        description: 'Trained dog and very Friendly',
    },
    {
        name: 'Cock',
        category: 'Cocks',
        image: '../Images/birds/eagle2.jpg',
        price:50,
        countInStock:12,
        rating:4.8,
        numReviews:20,
        description: 'Trained Cock and fighter',
    },
    {
         name: 'HEN',
         category: 'Cocks',
         image: '../Images/birds/hen.jpeg',
         price:60,
         countInStock:22,
         rating:4.8,
         numReviews:20,
         description: 'Trained Hen and fighter',
     },
     {
         name: 'GREEN RINGNECK Parrots',
         category: 'Birds',
         image: '../Images/birds/GREEN.PNG',
         price:50,
         countInStock:3,
         rating:5,
         numReviews:18,
         description: 'Beautiful green parrot 10 months age, Talking Mian Mithooo and Whistling, You can train accordingly',
     },
     {
         name: 'Mushka Murgha',
         category: 'Cocks',
         image: '../Images/birds/Mushka.PNG',
         price:35,
         countInStock:5,
         rating:4.9,
         numReviews:12,
         description: '',
         description: 'color black, age 1 year, group young, no special died, gender male',
     },
     {
         name: 'Turkey Bird',
         category: 'Birds',
         image: '../Images/birds/Turkey.PNG',
         price:120,
         countInStock:5,
         rating:4.7,
         numReviews:14,
         description: 'gender male, color white, age 1 year, active and healthy egg laying, group young',
     },
     {
         name: 'Fishery love Birds',
         category: 'Birds',
         image: '../Images/birds/Fishery.PNG',
         price:290,
         countInStock:2,
         rating:5,
         numReviews:11,
         description: 'healthy and active , home breead , age 9 months, grey in color',
     },
     {
         name: 'Asseel murga',
         category: 'Cocks',
         image: '../Images/birds/Asseel.PNG',
         price:95,
         countInStock:8,
         rating:4.9,
         numReviews:1,
         description: 'color black, age 6 months, full trained, active and healthy',
     },
    ],
}

export default Data;